import type { AbbreviationsData } from "./types";

/**
 * Static abbreviation mappings for BAS point name normalization.
 * Used as a fallback during fuzzy token matching when exact alias
 * matches from index.json don't hit.
 *
 * These mirror the mappings in the BAS Babel expand-aliases.ts script.
 */
export const abbreviationData: AbbreviationsData = {
  version: "1.0.0",
  abbreviations: {
    temperature: ["temp", "t", "tmp"],
    temp: ["temperature", "t", "tmp"],
    air: ["a", "ar"],
    supply: ["sup", "sa", "s", "sply"],
    return: ["ret", "ra", "r", "rtn"],
    outside: ["oa", "out", "outdoor", "o", "otsd"],
    outdoor: ["oa", "out", "outside", "o", "otsd"],
    mixed: ["ma", "mix", "m", "mxd"],
    exhaust: ["exh", "ea", "ex", "e"],
    relief: ["rel", "ra", "rlf"],
    discharge: ["da", "dis", "disch", "dschg"],
    fan: ["f", "fn"],
    pump: ["p", "pmp"],
    valve: ["vlv", "v", "vv"],
    damper: ["dmp", "dmpr", "d"],
    coil: ["cl", "c"],
    motor: ["mtr", "m"],
    unit: ["u", "unt"],
    chilled: ["chl", "ch", "chw", "cld"],
    chiller: ["chl", "ch", "chlr"],
    hot: ["ht", "hw", "h"],
    heating: ["htg", "heat", "ht", "h"],
    cooling: ["clg", "cool", "cl", "c"],
    condenser: ["cnd", "cw", "cond", "cdw"],
    boiler: ["blr", "b", "boil"],
    water: ["w", "wtr"],
    steam: ["stm", "st", "s"],
    setpoint: ["sp", "stpt", "set", "spt"],
    command: ["cmd", "c", "com"],
    status: ["sts", "stat", "st", "s"],
    enable: ["en", "enbl", "e"],
    output: ["out", "o", "op"],
    feedback: ["fb", "fdbk", "fdbck"],
    alarm: ["alm", "al", "a"],
    position: ["pos", "p", "psn"],
    speed: ["spd", "s", "sp"],
    frequency: ["freq", "frq", "f", "hz"],
    pressure: ["press", "prs", "p", "pr"],
    differential: ["diff", "dif", "d", "dp"],
    static: ["stat", "stc", "st", "s"],
    humidity: ["hum", "rh", "h"],
    relative: ["rel", "r"],
    dewpoint: ["dp", "dew", "dwpt"],
    enthalpy: ["enth", "ent", "h"],
    flow: ["flw", "fl", "f"],
    level: ["lvl", "lv", "l"],
    current: ["cur", "amp", "a", "i"],
    voltage: ["volt", "v", "vlt"],
    power: ["pwr", "pw", "p", "kw"],
    energy: ["nrg", "e", "kwh"],
    zone: ["zn", "z"],
    room: ["rm", "r"],
    space: ["spc", "sp", "s"],
    building: ["bldg", "bld", "b"],
    floor: ["flr", "fl", "f"],
    occupied: ["occ", "oc", "o"],
    unoccupied: ["unocc", "unoc", "un", "u"],
    standby: ["stby", "sby", "sb"],
    handling: ["hndl", "hnd", "h"],
    rooftop: ["rt", "rtu", "roof"],
    variable: ["var", "v", "vr"],
    constant: ["const", "con", "c"],
    primary: ["pri", "prim", "p"],
    secondary: ["sec", "scnd", "s"],
    tertiary: ["ter", "tert", "t"],
    economizer: ["econ", "eco", "e"],
    humidifier: ["hum", "humid", "h"],
    dehumidifier: ["dehum", "dh"],
    filter: ["flt", "fil", "f"],
    wheel: ["whl", "wh", "w"],
    heat: ["ht", "h"],
    entering: ["ent", "entr", "e", "in"],
    leaving: ["lvg", "leav", "lv", "l", "out"],
    inlet: ["in", "inlt", "i"],
    outlet: ["out", "outlt", "o"],
    basin: ["bsn", "bas", "b"],
    run: ["r", "rn"],
    start: ["str", "st", "s"],
    stop: ["stp", "st", "s"],
    reset: ["rst", "res", "r"],
    tower: ["twr", "tw", "t"],
    plant: ["plt", "pl", "p"],
    electric: ["elec", "el", "e"],
    gas: ["g", "gs"],
    fired: ["frd", "fr", "f"],
    isolation: ["iso", "isol", "i"],
    bypass: ["byp", "bp", "b"],
    mixing: ["mix", "mx", "m"],
    face: ["fc", "f"],
    stage: ["stg", "stge", "st"],
  },
  verboseExpansions: {
    temp: ["temperature"],
    t: ["temperature", "temp"],
    sa: ["supply air"],
    ra: ["return air", "relief air"],
    oa: ["outside air", "outdoor air"],
    ma: ["mixed air"],
    ea: ["exhaust air"],
    da: ["discharge air"],
    sp: ["setpoint", "static pressure"],
    dp: ["differential pressure", "dewpoint"],
    rh: ["relative humidity"],
    chw: ["chilled water"],
    hw: ["hot water"],
    cw: ["condenser water"],
    ahu: ["air handling unit", "air handler"],
    rtu: ["rooftop unit"],
    vav: ["variable air volume"],
    fcu: ["fan coil unit"],
    vrf: ["variable refrigerant flow"],
    cmd: ["command"],
    sts: ["status"],
    fb: ["feedback"],
    alm: ["alarm"],
    vlv: ["valve"],
    dmp: ["damper"],
    pmp: ["pump"],
    mtr: ["motor"],
  },
};
